repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.8.1
    hooks:
      - id: commitizen

  - repo: local
    hooks:
      - id: pre-commit-tasks
        name: Run pre-commit tasks
        entry: task pre-commit-checks
        language: system
        pass_filenames: false
        stages: [commit]
